name: test
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: [
          'yarn lint'
          'yarn test'
        ]
    env:
      command: ${{ matrix.command }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn
      - run: $command
        working-directory: .
